# Use the official NGINX base image
FROM nginx

# Copy the index.html file into the NGINX html directory
COPY index.html /usr/share/nginx/html/

# Expose port 80 (the default port for NGINX)
EXPOSE 80
